spring:
   application:
      name: springboot-redisson
#   redis:
#      redisson:
#         config: |
#            singleServerConfig:
#              password:
#              address: "redis://127.0.0.1:6379"
#              database: 1
#            threads: 0
#            nettyThreads: 0
#            codec: !<org.redisson.codec.FstCodec> {}
#            transportMode: "NIO"
server:
   port: 9888
